### ISSUE TITLE
In environment  variable supported?

### ISSUE THREAD

**Issue by anishmittal2020** [rogalmic/vscode-bash-debug#100]
I can't seem to debug my bash script that needs certain environment variables. Is it supported?

**Comment by rogalmic** [comment]
No, there is no explicit environment variables setting.

You can workaround it via creating separate *.sh script, where you can set variables and then [source](https://ss64.com/bash/source.html) the main script.

**Comment by anishmittal2020** [comment]
Thank you for your prompt response. Could you please document this in the limitations (README.md)? Also, please add any more limitations that you could think of.

**Comment by rogalmic** [comment]
`env` variables implemented in test release: 
https://github.com/rogalmic/vscode-bash-debug/releases/tag/untagged-9c1fed424470f1d1560b

Sample usage in `launch.json`:
```js
"env": {
  "MYVAR":"aaa    bbb ccc", 
  "MYVAR2": "bbb"
}
```

Be sure to uninstall extension manually and restart vscode before installing from vsix.

**Comment by rogalmic** [comment]
Implemented...
