### ISSUE TITLE
Debug scripts with root priviliges

### ISSUE THREAD

**Issue by dagi12** [rogalmic/vscode-bash-debug#109]
Is there a way to run script with root privileges with configuration option or somekind of workaround. I tried to put "sudo" in launch.json but with no luck.

**Comment by rogalmic** [comment]
No there is no option for that.

As a workaround, i see 2 options:
1. https://askubuntu.com/questions/803343/how-to-run-visual-studio-code-as-root/1027243

2. change every command in script that requires elevation to start with sudo, (hint: https://stackoverflow.com/questions/82256/how-do-i-use-sudo-to-redirect-output-to-a-location-i-dont-have-permission-to-wr) - sudo will ask for password only once

**Comment by dagi12** [comment]
That helped enough.

**Comment by mbronni** [comment]
Please add "sudo": true in the configuration file and then run the script with sudo priviliges
