### ISSUE TITLE
calling another script stops the debugger

### ISSUE THREAD

**Issue by MaurGi** [rogalmic/vscode-bash-debug#111]
I have `scriptA.sh` that calls `scriptB.sh` via simple execution - right now the debugger executes `./scriptB.sh` as a single line of code and I cannot debug it.
Is there a way to "step into" `scriptB.sh`?

thx

**Comment by rogalmic** [comment]
The only way to do that with debugging is to use bash 'source' built in command.

https://en.m.wikipedia.org/wiki/Source_(command)

**Comment by rogalmic** [comment]
Closing that, please reopen if  needed...
