### ISSUE TITLE
_Dbg_fdi: No such device or address

### ISSUE THREAD

**Issue by buongiorno999** [rogalmic/vscode-bash-debug#112]
For years, I have looking for a real bash debugger.  I think I found it. Thanks a lot for your work.

When I start the debugger, I get the following error message
/home/oracle/.vscode/extensions/rogalmic.bash-debug-0.3.5/bashdb_dir/command/source.sh: line 41: _Dbg_fdi: No such device or address

I hope have provided you will all the info you might need.

operating system Centos 7

$ bashdb --version
bashdb, release 4.4-1.0.1

$ bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

$ code --version
1.35.1
c7d83e57cd18f18026a8162d042843bda1bcf21f
x64

$ bash -c 'uname -a; for P in bash bashdb cat mkfifo pkill; do echo ---; which -a $P; command $P --version; done'
Linux Z800.ldom 3.10.0-957.21.2.el7.x86_64 #1 SMP Wed Jun 5 14:26:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
---
/usr/bin/bash
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
---
/usr/bin/bashdb
bashdb, release 4.4-1.0.1
---
/usr/bin/cat
cat (GNU coreutils) 8.22
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjörn Granlund and Richard M. Stallman.
---
/usr/bin/mkfifo
mkfifo (GNU coreutils) 8.22
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
---
/usr/bin/pkill
pkill from procps-ng 3.3.10

## Debug output
    "version": "0.2.0",
    "configurations": [
        
         {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug (simplest configuration)",
            "program": "${file}"
            "showDebugOutput": true,
            "trace": true
        }
    ]
}

To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest":false,"supportsEvaluateForHovers":true,"supportsStepBack":false,"supportsSetVariable":false}}
From client: launch({"type":"bashdb","request":"launch","name":"Bash-Debug (simplest configuration)","program":"/home/oracle/Downloads/test/test.sh","showDebugOutput":true,"trace":true,"args":[],"env":{},"cwd":"/home/oracle/5000_MSVisual_Studio","pathBash":"bash","pathBashdb":"/home/oracle/.vscode/extensions/rogalmic.bash-debug-0.3.5/bashdb_dir/bashdb","pathBashdbLib":"/home/oracle/.vscode/extensions/rogalmic.bash-debug-0.3.5/bashdb_dir","pathCat":"cat","pathMkfifo":"mkfifo","pathPkill":"pkill","__sessionId":"a171d9d5-3b05-4bc2-9517-e4afbe19c5c2"})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"::PROXYID::30519\n"}}
::PROXYID::30519
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"/home/oracle/.vscode/extensions/rogalmic.bash-debug-0.3.5/bashdb_dir/command/source.sh: line 41: _Dbg_fdi: No such device or address\n"}}
/home/oracle/.vscode/extensions/rogalmic.bash-debug-0.3.5/bashdb_dir/command/source.sh: line 41: _Dbg_fdi: No such device or address

**Comment by rogalmic** [comment]
Please try setting the "terminalKind" in `launch.json` to "integrated" or "external", according to readme:
```
Limitations and known problems
Use terminalKind@launch.json set to integrated or external for interactive scripts (using stdin)
```

**Comment by buongiorno999** [comment]
It works.  Thanks for the quick answer.

**Comment by masterjian** [comment]
yes it works too.
My Environment：
Windows 11
VSCode 1.8
WSL2

installed the plugin bashdb debuger.

thanks, awesome tool
