### ISSUE TITLE
DEBUG IN 'DEBUG CONSOLE'

### ISSUE THREAD

**Issue by LANPAST** [rogalmic/vscode-bash-debug#118]
WINDOWS10 1903

## Executables
Version of bash-debug: 0.3.2
WSL bash.exe Version: 10.0.15063.0
WSL bash version: 4.3.48(1)-release
WSL bashdb version: bashdb, release 4.3-0.91
WSL Distro: Ubuntu 18.04 LTS
Output of following commands (on windows, execute them in Command Prompt or PowerShell):

```
where bash
bash: /bin/bash /etc/bash.bashrc /mnt/c/Windows/system32/bash.exe /usr/share/man/man1/bash.1.gz
code --version
Linux DESKTOP-BPEOIL7 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## Debug output
/home/lan/.vscode-server/extensions/rogalmic.bash-debug-0.3.5/bashdb_dir/command/source.sh: line 41: /dev/stdin: No such device or address

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug (type in script name)",
            "cwd": "${workspaceFolder}",
            "program": "${command:AskForScriptName}",
            "args": []
        },
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug (select script from list of sh files)",
            "cwd": "${workspaceFolder}",
            "program": "${command:SelectScriptName}",
            "args": []
        },
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug (hardcoded script name)",
            "cwd": "${workspaceFolder}",
            "program": "${workspaceFolder}/path/to/script.sh",
            "args": []
        },
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug (simplest configuration)",
            "program": "${file}"
        }
    ]
}
```

## Details
When I debug, my output is displayed in DEBUG CONSOLE,
I can't debug in the terminal.
So I can't interact with the program either.
Please tell me how to debug in the terminal.

**Comment by LANPAST** [comment]
I saw the GIF in the introduction, like 
https://raw.githubusercontent.com/rogalmic/vscode-bash-debug/gif/images/bash-debug-samp-launch-autoconfig.gif
He can debug in the terminal. I don't know how to set it up.

**Comment by rogalmic** [comment]
Since there were some issues with terminal usage, the default is debug console. 

It can be switched by specifying `terminalKind` in `launch.json`:

```
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug (simplest configuration)",
            "program": "${file}",
            "terminalKind": "integrated" // or "external"
        }
```

**Comment by LANPAST** [comment]
> 
> 
> Since there were some issues with terminal usage, the default is debug console.
> 
> It can be switched by specifying `terminalKind` in `launch.json`:
> 
> ```
>         {
>             "type": "bashdb",
>             "request": "launch",
>             "name": "Bash-Debug (simplest configuration)",
>             "program": "${file}",
>             "terminalKind": "integrated" // or "external"
>         }
> ```

Thanks.Now I can debug in the terminal.
