### ISSUE TITLE
"/dev/stdin: No such device or address" message when running Bash Debug in VSCode

### ISSUE THREAD

**Issue by tkumark** [rogalmic/vscode-bash-debug#134]
OS: Ubuntu 18.04
Bash Debug 0.3.7

I am running VScode on my Ubuntu 18.04. When I run the program with in the debug console I get the following error message 

> /home/kumar/.vscode/extensions/rogalmic.bash-debug-0.3.7/bashdb_dir/command/source.sh: line 41: /dev/stdin: No such device or address
> test
> test2
> bash: line 1: 19997 Killed                  "bash" "/home/kumar/.vscode/extensions/rogalmic.bash-debug-0.3.7/bashdb_dir/bashdb" --quiet --tty "/tmp/vscode-bash-debug-fifo-15522" --tty_in "/tmp/vscode-bash-debug-fifo-15522_in" --library "/home/kumar/.vscode/extensions/rogalmic.bash-debug-0.3.7/bashdb_dir" -- "/home/kumar/DevWrkSpc/bashwrkspace/test.sh"

Is this expected message or have I configured it wrong? 
Please note I am new to Linux development and VSCode might be a dumb question.

Thanks

**Comment by rogalmic** [comment]
There is terminalKind setting in launch. Json. Please try different options, since default 'debugconsole' does not support stdin, as mentioned in Readme.

**Comment by crypdick** [comment]
For anyone else encountering this issue, this `launch.json` worked for me:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "bashdb",
            "request": "launch",
            "terminalKind": "integrated" ,
            "name": "Bash-Debug (simplest configuration)",
            "program": "${file}"
        }
    ]
}
```

**Comment by LPfly0822** [comment]
thank you,useful
