### ISSUE TITLE
Debug Chains of scripts

### ISSUE THREAD

**Issue by cycollins** [rogalmic/vscode-bash-debug#136]
I'm using version 0.3.7, but really this is more of an operational question and perhaps an enhancement request. Since one script often calls another and so forth, is there a way to "step into" a called script as with the environment and parameters specified in the calling script. Obviously the literal "step into" command doesn't work, but some mechanism for getting "into" the called script would be of general use to all I would think. It would be fine if the calling script had to be modified (say, for example, calling the "child" script via bashdb ). It would also be fine if the called script had to call, say, a read or some blocking call and the "attach" directive then worked to bridge the two scripts. If there is a way (even an ungainly way) to do this, I'd be interesting in using this technique. If there isn't, might such a mechanism be possible to add to Bash Debug, or is the hook mechanism you employ simply unable to switch script contexts like that? Thanks.

**Comment by rogalmic** [comment]
It should work with bash 'source' directive. When just run a script in another, it will not work, since it will be separate bash process.
