### ISSUE TITLE
Accept additional parameter `commandline` for arguments in string

### ISSUE THREAD

**Issue by felipecassiors** [rogalmic/vscode-bash-debug#138]
VS Code does not support passing arguments to `args` in a string instead of an array of string. See https://github.com/microsoft/vscode/issues/83678.

However, due to that, is impossible for users to use "prompt for arguments" when launching a debug session. 

VS Code team suggest the extension owners to provide an additional parameter for debbuging configuration. See https://github.com/microsoft/vscode/issues/83678#issuecomment-592600592

It would look like then:
```JSON
{
  "version": "0.2.0",
  "configurations": [
      {
        "type": "bashdb",
        "request": "launch",
        "name": "Bash-Debug (simplest configuration)",
        "program": "${file}",
        "cwd": "${workspaceFolder}",
        "commandline": "-foo -bar /hello/world -o -p"
      }
    ]
}
```
And then, we would be able to do something like:
```JSON
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "bashdb",
      "request": "launch",
      "name": "Bash-Debug (simplest configuration)",
      "program": "${file}",
      "cwd": "${workspaceFolder}",
      "commandline": "${input:arguments}"
    }
  ],
  "inputs": [
    {
      "id": "arguments",
      "type": "promptString",
      "default": "--help",
      "description": "The arguments to pass to the script"
    }
  ]
}

```

**Comment by rogalmic** [comment]
This will break the integrated/external terminal, since the vscode api used for those requires array of args. See RunInTerminalRequest + RunInTerminalRequestArguments.

Having said that, I would also prefer to pass full args as one string, but it will be possible  only when mentioned api methods allow to specify to use bash explicitly + provide command as single string.

**Comment by felipecassiors** [comment]
So how about transforming the commandline string into an array?

**Comment by rogalmic** [comment]
Well, this requires handling of arg quoting, which proves to be hard and should not be part of extension. Args are sometimes more complex values.

**Comment by felipecassiors** [comment]
@rogalmic do you mind taking a look at https://github.com/microsoft/vscode/issues/97655 and cast your vote if you agree?
