### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by GitMensch** [rogalmic/vscode-bash-debug#142]
The [Open VSX Registry](https://open-vsx.org/?search=bash) does not include a debugger for bash yet. It is the default extension provider of free "vscode" builds and it would be good to find this extension there, too.

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by rogalmic** [comment]
Something like this?
https://github.com/rogalmic/vscode-bash-debug/pull/143

**Comment by GitMensch** [comment]
Yes (likely needs some setup and registration before).

**Comment by rogalmic** [comment]
I already set up namespace and token, plus i added token to travis. Will run build shortly.

**Comment by rogalmic** [comment]
🚀  Published rogalmic.bash-debug v0.3.9, not sure how to check though.

**Comment by GitMensch** [comment]
Thanks for https://open-vsx.org/extension/rogalmic/bash-debug !
