### ISSUE TITLE
How can I debug a called subscript?

### ISSUE THREAD

**Issue by serbenet** [rogalmic/vscode-bash-debug#148]
Hi,

"Step into" does not seem to work when another subscript is called. The subscript is simply simply ran and the debugger does not step into it. Is there a way to cause the second script to also run in the debugger?

Thanks in advance

Serbenet

**Comment by rogalmic** [comment]
Are you using bash "source" keyword? Dot (.) is also short for source...

**Comment by serbenet** [comment]
No I am not using the source keyword.

**Comment by rogalmic** [comment]
Step into works only for scripts called with source keyword. Calling script directly will start separate process.

**Comment by serbenet** [comment]
To me this is a major limitation since calling subscripts is a very common practice in bash scripts. And not being able to debug those subscripts is limiting the interest of this extension.
If somehow, this could be addressed in a future version, this would be great.

Thanks

**Comment by rogalmic** [comment]
Like explained, the only way to debug subscript is to call it following way inside your script:
"source  ./subscript. sh"

There is no technical way to debug separate bash subprocess.
