### ISSUE TITLE
windows 10 Error: cwd (/mnt/d/***/****/) does not exists

### ISSUE THREAD

**Issue by Chamiduz** [rogalmic/vscode-bash-debug#151]
I am getting "`Error: cwd (/mnt/d/***/***/***/***) does not exists`" while trying to debug using Bash Debug extension with vscode

![image](https://user-images.githubusercontent.com/37238842/110656153-b212c300-81e5-11eb-99c5-91582a9a4061.png)

https://github.com/microsoft/vscode/issues/118618

Actual file path : `D:\***\***\***\***`
VS Code Version : `1.54.1 user setup`
OS Version : `windows 10 pro 1909`

Steps to Reproduce:

1. Install vscode
2. Install Remote-WSL extension 0.54.2
3. Install Bash Debug extension 0.3.9
4. Create launch.json

```
<img width="418" alt="vscodeerror" src="https://user-images.githubusercontent.com/37238842/110613819-b3c59200-81b7-11eb-8116-0628f4ecf521.PNG">

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash simple",
            "cwd": "${workspaceFolder}",
            "program": "${file}",
            "terminalKind": "integrated"  
        }
    ]
}

```
5. Start debugging

**Comment by jeremyMonatte** [comment]
Is there a solution so ? 
Having the same issue

**Comment by zagadelha** [comment]
This not works for me too. Unfortunately.

**Comment by rogalmic** [comment]
Please try setting both wsl and program in launch.json manually with full path in wsl:
```
            "cwd": "/mnt/d/some/path", //path to workspace
            "program": "/mnt/d/some/path/script_to_debug.sh", //path to file
```
