### ISSUE TITLE
Error: cwd ... does not exist.

### ISSUE THREAD

**Issue by ivavid** [rogalmic/vscode-bash-debug#161]
## Executables
Bash debug: 0.3.9
vscode: 1.65-insider
OS: Windows 10

```bash
PS C:\Users\user123> where bash
PS C:\Users\user123> # if `code` not found on macOS, follow the instructions in:
PS C:\Users\user123> # https://code.visualstudio.com/docs/setup/mac
PS C:\Users\user123> code --version
code: The term 'code' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\user123> bash -c 'uname -a; for P in bash bashdb cat mkfifo pkill; do echo ---; which -a $P; command $P --version; done'
Linux MMO-TO6735-1 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
---
/usr/bin/bash
/bin/bash
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
---
/bin/bash: bashdb: command not found
---
/usr/bin/cat
/bin/cat
cat (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjorn Granlund and Richard M. Stallman.
---
/usr/bin/mkfifo
/bin/mkfifo
mkfifo (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
---
/usr/bin/pkill
/bin/pkill
pkill from procps-ng 3.3.16
```

## Debug output
No debug output. My launch.json is as follows:

```javascript
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug",
            "cwd": "${workspaceFolder}",
            "program": "${file}",
            "args": [],
            "showDebugOutput": true,
            "trace": true
        }
    ]
}
```

## Details
When running debug the following error appears:
`Error: cwd ... does not exist.`
![bash_debug_error](https://user-images.githubusercontent.com/223638/153032298-a72654ff-eabb-4634-81d7-3de2b9b6d001.png)

Expected behavior: Debug start without errors.

May be related to issue #151.

**Comment by jmal1** [comment]
Also seeing this issue

**Comment by Gebhartj** [comment]
Also seeing this issue

**Comment by rogalmic** [comment]
Please try setting both wsl and program in launch.json manually with full path in wsl:
```
            "cwd": "/mnt/d/some/path", //path to workspace
            "program": "/mnt/d/some/path/script_to_debug.sh", //path to file
```

**Comment by Gebhartj** [comment]
> 

"program": "\\x\\pkm\\onyxnote.sh",
"pathBash": "C:\\msys64\\mingw64.exe",
"cwd": "\\x\\pkm\\"

**Comment by Gebhartj** [comment]
> Please try setting both wsl and program in launch.json manually with full path in wsl:
> 
> ```
>             "cwd": "/mnt/d/some/path", //path to workspace
>             "program": "/mnt/d/some/path/script_to_debug.sh", //path to file
> ```
I try this
"program": "\x\pkm\onyxnote.sh",
"pathBash": "C:\msys64\mingw64.exe",
"cwd": "\x\pkm\"

![image](https://user-images.githubusercontent.com/34003931/166697939-85093a6f-e6dd-450e-96b7-3aacd1c1ab75.png)



And this 
"program": "/x/pkm/onyxnote.sh",
"pathBash": "C:/msys64/mingw64.exe",
"cwd": "/x/pkm"

![image](https://user-images.githubusercontent.com/34003931/166698456-a375a57f-44de-4884-91bc-f1b5ec7ce386.png)

**Comment by rogalmic** [comment]
Mingw is not supported AFAIK, you need to use wsl. 

In wsl there is a filesystem which maps "C:\" to "mnt/c", extension automates the conversion.  Absolute path should work in case of issues.

**Comment by Gebhartj** [comment]
Thanks, I've also read that you support wsl. I was hoping it would work with MINGV. I can't use wsl because it requires virtualisation and it doesn't work for me.

**Comment by rogalmic** [comment]
There was a problem with fifo files support, otherwise i would have added those.

https://github.com/rogalmic/vscode-bash-debug/issues/99

**Comment by shangerxin** [comment]
I have the same issue. It is resolved by:

1. Install WSL ubuntu
2. Set ubuntu as the default WSL container by 
```
$ wsl --set-default <ubuntu-distribution-name>
```
4. Add bash debug configuration from VSCode
5. Start debugging.

The root cause of this is due to I have installed Windows docker which is replaced the default WSL container from ubuntu to docker. 

Hope this helps. Cheers.
