### ISSUE TITLE
"bashdb: command not found"

### ISSUE THREAD

**Issue by sdolenc** [rogalmic/vscode-bash-debug#18]
I get a popup that says:
"Debug adapter process has terminated unexpectedly"

The debug console also says:
"bash: line 17: bashdb: command not found"

I've reproduced this error on Ubuntu 14 and 16 using VS Code 1.7.1 and 1.7.2.

**Comment by rogalmic** [comment]
The problem is that bashdb is most likely not installed ("sudo apt-get install bashdb"). I will try to make some meaningful error message in that case + describe it better in info page. 

So, still open...

**Comment by sdolenc** [comment]
oh cool. thanks!

**Comment by rogalmic** [comment]
Added information to extension readme file.

**Comment by linhadiretalipe** [comment]
If you are using Mac you need to instal by brew.

brew install bashdb
