### ISSUE TITLE
mktemp: illegal option -- -

### ISSUE THREAD

**Issue by m-thomson** [rogalmic/vscode-bash-debug#19]
On MacOS I'm seeing the following error when trying to start a debug session:

<img width="746" alt="screenshot_3dfb6f" src="https://cloud.githubusercontent.com/assets/5273016/21746951/9be17896-d50b-11e6-8bfd-2f70698073ba.png">

**Comment by m-thomson** [comment]
It turns out that mktemp on MacOS doesn't support the "--dry-run" option flag. It needs to be changed to "-u" on line 75 https://github.com/rogalmic/vscode-bash-debug/blob/6714b2f7e190030ce1e37d2d3336cd3983206bf5/src/bashDebug.ts

This change worked for me but to be honest I'm not exactly sure the flags are 100% equivilant. The man page for MacOS mktemp says:

> -u  Operate in 'unsafe' mode.  The temp file will be unlinked before mktemp exits.  This is slightly better than mktemp(3) but still introduces a race condition.  Use of this option is not encouraged.

**Comment by rogalmic** [comment]
Yes, I think it is safe to change that:

_" -u, --dry-run       do not create anything; merely print a name (unsafe)"_

**Comment by rogalmic** [comment]
Usage of mktemp was removed, better to handle that internally in typescipt code...
