### ISSUE TITLE
Troubles with script about 1K of lines/or 100K size.

### ISSUE THREAD

**Issue by belonesox** [rogalmic/vscode-bash-debug#22]
I see troubles (hangs of debugger) with relatively small and trivial scripts
for example:
https://gist.github.com/belonesox/5bf3b1cbc3f1ae3b8ca26cf0e6168184
(1000 lines of comments).

raw bashdb works OK with it.

May be some hardcoded limits?

I wish to debug enourmous generated "configure" scripts (≈30K lines, ≈700K).

**Comment by rogalmic** [comment]
I can reproduce this with provided file. 

There should not be any hardcoded limit set. This looks like some race condition in debugger vs UI startup (might be that some input/output gets omitted in parsing). Loading bigger file takes more time.

I will need to take a closer look at this when I have some free time...

**Comment by rogalmic** [comment]
@belonesox : please try following version and post the results here:

[bash-debug-0.0.4.vsix.zip](https://github.com/rogalmic/vscode-bash-debug/files/709360/bash-debug-0.0.4.vsix.zip)

**Comment by belonesox** [comment]
Looks OK, thank you very much!
