### ISSUE TITLE
how can i change `pwd` to the script directory

### ISSUE THREAD

**Issue by Tyzual** [rogalmic/vscode-bash-debug#25]
for example, i have a bash script in /some/dir/bash.sh
when i run the script, i always cd to /some/dir and the pwd command generate /some/dir
however in vscode, the pwd command generate '/' which is not exptected

**Comment by rogalmic** [comment]
I cannot reproduce this.

Here is what i do in test script:
`#!/bin/bash`

`cd ~/Documents`
`pwd`

This script ouputs /home/"user"/Documents correctly (at least in my Kubuntu system).

Can you provide steps to reproduce the problem + system info?

**Comment by Tyzual** [comment]
I mean I cd to /some/dir in terminal and run the script in terminal, the pwd command get /some/dir.
however, in VSCode, I open /some/dir folder, and run the script in VSCode. the pwd get '/'.

**Comment by rogalmic** [comment]
You can always create second script, where you have 2 lines:
`cd "/your/dir"`
`source "/your/dir/script.sh"`

However, maybe better idea is to use $BASH_SOURCE instead of pwd (which is path to root script), as it is independent of execution context.

**Comment by rogalmic** [comment]
Added "cwd" parameter to version 0.1.1 - please verify.

**Comment by rogalmic** [comment]
I think this is fixed, please re-open if needed...
