### ISSUE TITLE
I can't get output 

### ISSUE THREAD

**Issue by Funnyang** [rogalmic/vscode-bash-debug#31]
when I use it, I only get output from console, but not in output. Is it normal?   (macOS 10.12.5)
<img width="1197" alt="2017-06-15 2 33 21" src="https://user-images.githubusercontent.com/9402399/27169092-fd81c2e4-51da-11e7-88b4-13aaf5a6bd55.png">
<img width="1179" alt="2017-06-15 2 33 34" src="https://user-images.githubusercontent.com/9402399/27169096-007e0476-51db-11e7-867f-cb19773cae3a.png">

**Comment by rogalmic** [comment]
Yes, this is how it was designed to work. The vscode debugger extension api has access to "debug console".

**Comment by Funnyang** [comment]
OK, thank you very much!
