### ISSUE TITLE
define execute location

### ISSUE THREAD

**Issue by antorax** [rogalmic/vscode-bash-debug#32]
I am trying to use this plugin to debug a script that checks moves and deletes files. i have a test dir resembling the operational server. this project is located in a git dir and most paths used in the script are relative paths. this plugin wants to run my script in /home/$USER (this is confirmed by the pwd variable)
i would like to run it in /home/$USER/git/ProjectDir. how can i force this to happen? do i set this in launch.json?

**Comment by rogalmic** [comment]
Please try to create second script, that cd's to desired folder, then uses "source" bash builtin to include the original script. Debug that second script.

**Comment by antorax** [comment]
what worked best for me was to add a SCRIPT_ROOT variable and then assign all path variables like
PATH="$SCRIPT_ROOT"/path/to/dir that way i can easily change the location everything is run from.

**Comment by rogalmic** [comment]
Added "cwd" parameter to version 0.1.1 - please verify.

**Comment by rogalmic** [comment]
I think this is fixed, please re-open if needed...
