### ISSUE TITLE
Is the tag v0.1.0 incorrect?

### ISSUE THREAD

**Issue by wataash** [rogalmic/vscode-bash-debug#35]
[CHANGELOG.md @ tag/v0.1.0](https://github.com/rogalmic/vscode-bash-debug/blob/v0.1.0/CHANGELOG.md) reads "Bugfix release v0.0.8".
Perhaps it causes contradictive information in the installation window of Bash Debug ("0.0.8" is "Bugfix release v0.1.0").

![image](https://user-images.githubusercontent.com/4846670/31052609-660690fe-a6c4-11e7-9a39-408ed6f6fbae.png)

**Comment by rogalmic** [comment]
This is an error i noticed already, changelog will be fixed in next
release. The biggest problem right now is that I do not have time to make
the release process automated, to solve problem with manual errors...

2017-10-01 9:36 GMT+02:00 Wataru Ashihara <notifications@github.com>:

**Comment by wataash** [comment]
Thanks for quick response.
Okay if you are aware of it :smiley:
