### ISSUE TITLE
Issue reading user input when debugging

### ISSUE THREAD

**Issue by HomeBrewCrew** [rogalmic/vscode-bash-debug#37]
When debugging I'm not able to get it to prompt for the user input on a read command. I recorded a short screen grab of the issue I'm seeing and threw it up on Youtube if it helps.

https://youtu.be/3VaMEmBNH_8

**Comment by rogalmic** [comment]
This is current limitation - debugging works only for non interactive scripts. I am not yet sure how to make it make it work, since when running bashdb both debugger control and script input come from same source (stdin)...

I will need to make a notice about that in limitations section of readme.
