### ISSUE TITLE
VSCode is no longer supporting specifiying a commandId in the "initialConfigurations" contribution

### ISSUE THREAD

**Issue by isidorn** [rogalmic/vscode-bash-debug#39]
Hi,

We noticed your extension in `package.json` is using a `"initialConfigurations"` contribution in a deprecated way by specifiying a command id.
We wanted to let you know that we plan to delete support for this specific use of "initialConfigurations" soon.
More about this deprecation can be found [here](https://github.com/Microsoft/vscode/issues/33791) and in our release notes.
A good example on how to use the `DebugConfigurarationProvider` which is the new way of doing this can be found [here](https://github.com/Microsoft/vscode-node-debug/blob/d61ac00e16069fe63a5a5b6c65a4040de013e7f2/src/node/extension/configurationProvider.ts#L18)

Also note other deprecations which are specified in our release notes (which can be found on our site).

Kind regards,
Isidor from the VSCode team

**Comment by tusharvjoshi** [comment]
I got hit by this issue today.  The extension refused to provide configurations and I have to copy them manually from source to the launch.json file like below:

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
		{
			"name": "Bash-Debug (hardcoded script name)",
			"type": "bashdb",
			"request": "launch",
			"scriptPath": "${workspaceRoot}/agent_memo.sh",
			"commandLineArguments": "",
			"windows": {
				"bashPath": "C:\\Windows\\sysnative\\bash.exe"
			},
			"linux": {
				"bashPath": "bash"
			},
			"osx": {
				"bashPath": "bash"
			}
		},
		{
			"name": "Bash-Debug (select script from list of sh files)",
			"type": "bashdb",
			"request": "launch",
			"scriptPath": "${command:SelectScriptName}",
			"commandLineArguments": "",
			"windows": {
				"bashPath": "C:\\Windows\\sysnative\\bash.exe"
			},
			"linux": {
				"bashPath": "bash"
			},
			"osx": {
				"bashPath": "bash"
			}
        },
		{
			"name": "Bash-Debug (type in script name)",
			"type": "bashdb",
			"request": "launch",
			"scriptPath": "${workspaceRoot}/${command:AskForScriptName}",
			"commandLineArguments": "",
			"windows": {
				"bashPath": "C:\\Windows\\sysnative\\bash.exe"
			},
			"linux": {
				"bashPath": "bash"
			},
			"osx": {
				"bashPath": "bash"
			}
        }
	]
}`

**Comment by AntonKrug** [comment]
Same, I get only this when I use the command to generate configuration:

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": "extension.bash-debug.provideInitialConfigurations"
}
