### ISSUE TITLE
Configuration Options not Displayed After Selecting "Bash Debug"

### ISSUE THREAD

**Issue by robertpeteuil** [rogalmic/vscode-bash-debug#45]
Does this extension do anything Windows specific when initially setting up `launch.json`?

I'm having an issue on both macOS and Ubuntu 16.04.  Both systems have the latest version of vscode, the latest extension version and pre-reqs installed.

When I follow the steps listed under Usage:
- Press ctrl+shift+P (cmd+shift+P) and run "Debug: Open launch.json"
- Select "Bash Debug"

Instead of displaying a menu as shown in the video, it opens `launch.json` containing the code below.  Note: `launch.json` did not exist prior to this.

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": "extension.bash-debug.provideInitialConfigurations"
}
```

If I manually populate `launch.json` with contents from this repo the debugger works.  Obviously this doesn't scale, as it required manually populating it for every project and changing it for different debugging options.

**Comment by fixedmachine** [comment]
Same here. Please fix it.

**Comment by robertpeteuil** [comment]
How was this given a thumbs down? 

The video embedded in the README clearly shows the automatic generation of `launch.json` after selecting "Bash Debug".

If I'm doing something wrong please tell me - don't just downvote my question!

**Comment by fixedmachine** [comment]
@robertpeteuil sorry, something went wrong with "thumbs".

**Comment by rogalmic** [comment]
After breaking change in vscode debug protocol, we added initial configuration that should work. There are also configuration snippets for the drop down/input boxes...

Please verify....

**Comment by robertpeteuil** [comment]
Yes, it's working.

While I dont get the menu driven selection - at least I get a working beugger for the current file, which is great.

Here's what it generated (comments removed):

``` json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "bashdb",
      "request": "launch",
      "name": "Bash-Debug (simplest configuration)",
      "program": "${file}"
    }
  ]
}
```

**Comment by rogalmic** [comment]
Yes, this is the expected behaviour now. When you click 'Add configuration' button, there are options from previous version:
![image](https://user-images.githubusercontent.com/23117003/37560432-277db086-2a38-11e8-8a6d-76229bf14911.png)

In Debug pane on the left hand side, the current configuration can be selected from combo (if there is more than one).

![image](https://user-images.githubusercontent.com/23117003/37560453-855020c2-2a38-11e8-9fe2-ed6dd01f5cf7.png)


Thank you for testing this.
