### ISSUE TITLE
What is the correct syntax that I should write in launch.json to debug my file

### ISSUE THREAD

**Issue by macnux** [rogalmic/vscode-bash-debug#46]
Hi,

When I click debug, I expect the debugger to stop at my breakpoint like other IDEs.
I noticed that I need to write something in launch.json to run my debugging session.
What is the correct syntax that I should write in launch.json to debug my file?

Regards,

**Comment by chriad** [comment]
Hi, 
I just had the same issue and didn't understand what to put into `launch.json`. I think you can just paste the following into `launch.json` (see #39)


```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
		{
			"name": "Bash-Debug (hardcoded script name)",
			"type": "bashdb",
			"request": "launch",
			"scriptPath": "${workspaceRoot}/agent_memo.sh",
			"commandLineArguments": "",
			"windows": {
				"bashPath": "C:\\Windows\\sysnative\\bash.exe"
			},
			"linux": {
				"bashPath": "bash"
			},
			"osx": {
				"bashPath": "bash"
			}
		},
		{
			"name": "Bash-Debug (select script from list of sh files)",
			"type": "bashdb",
			"request": "launch",
			"scriptPath": "${command:SelectScriptName}",
			"commandLineArguments": "",
			"windows": {
				"bashPath": "C:\\Windows\\sysnative\\bash.exe"
			},
			"linux": {
				"bashPath": "bash"
			},
			"osx": {
				"bashPath": "bash"
			}
        },
		{
			"name": "Bash-Debug (type in script name)",
			"type": "bashdb",
			"request": "launch",
			"scriptPath": "${workspaceRoot}/${command:AskForScriptName}",
			"commandLineArguments": "",
			"windows": {
				"bashPath": "C:\\Windows\\sysnative\\bash.exe"
			},
			"linux": {
				"bashPath": "bash"
			},
			"osx": {
				"bashPath": "bash"
			}
        }
	]
}

```

As noted in #45, this needs to be done manually if I understand correctly.

**Comment by robertpeteuil** [comment]
@macnux  What Platform are you encountering this issue on?  I suspect that the menu driven auto-creation portion of this extension is either platform specific, or it's been broken by changes in newer builds of VSCode. 

As I mentioned in #45, populating `launch.json` manually works.  But, according to the instructions this shouldn't be necessary. 
- The README video demonstrates automatic generation of this file after a series of menu questions. 
- The instructions do not specify the need to do this, nor is there any information on how to do this.
- I found the contents to put into `launch.json` by searching through the extension source, and extracting the data that it's supposed to auto populate.
