### ISSUE TITLE
Add hint about bashdb 4.4-0.94 supporting "set -e" / "set -errexit"?

### ISSUE THREAD

**Issue by mlocati** [rogalmic/vscode-bash-debug#55]
In the main README we can read that we can't use `set -e` (aka `set -errexit`) in bash scripts.

BTW, latest [avaialble bashdb](https://sourceforge.net/projects/bashdb/files/bashdb/) *does* support scripts with this flag.

So, what about adding a note to this in the README?

**Comment by rogalmic** [comment]
Great to hear! Which version of bashdb does support it?

**Comment by wataash** [comment]
The title explain it?

**Comment by mlocati** [comment]
It has been fixed since 2017-08-01 (see https://sourceforge.net/p/bashdb/code/ci/master/tree/ChangeLog), so I think version 4.4-0.93

**Comment by rogalmic** [comment]
Yep, it is in the title :)

**Comment by mlocati** [comment]
> Yep, it is in the title :)

Well, in the title I wrote 4.4-0.**94**, but from the changelog it seems to be available since 4.4-0.**93** (my fault :wink:)

**Comment by rogalmic** [comment]
Note added:

> Executing set -e causes debugging script to exit (bashdb fixes this in version 4.4-0.93). Consider using trap 'exit $?' ERR.

I believe this can be closed...

**Comment by mlocati** [comment]
:+1:
