### ISSUE TITLE
Undefined symbol: sh_xfree

### ISSUE THREAD

**Issue by antonio-petricca** [rogalmic/vscode-bash-debug#73]
Hi, I am using:

> Linux Mint 19 / Ubuntu 18.04
> VS Code Insiders (daily release)
> GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
> bashdb, release 4.3–0.91

When I start debugging I get this error:

`/bin/bash: symbol lookup error:  /usr/share/bashdb/builtin/set0: undefined symbol: sh_xfree`

**Comment by rogalmic** [comment]
Does bashdb work when running it directly from shell commandline?

Please try uninstalling bash and compiling it manually:
```
wget https://netix.dl.sourceforge.net/project/bashdb/bashdb/4.4-0.94/bashdb-4.4-0.94.tar.gz
tar -xvfz bashdb-*.tar.gz
cd bashdb-*
./configure
make
sudo make install
```

**Comment by antonio-petricca** [comment]
I does not work from shell command line too! :-1: 

I installed it as you suggested me, and now works in shell command line. :+1: 

I am going to try it inside VS Code...

**Comment by antonio-petricca** [comment]
Here is my configuration:

```json
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug (hardcoded script name)",
            "cwd": "${workspaceFolder}",
            "program": "${workspaceFolder}/ci/scripts/pipeline-configure",
            "args": []
        }
```
Here is the screenshot:

![pipeline-configure - ci-template - visual studio code - insiders_006](https://user-images.githubusercontent.com/6660386/42703468-fee25a68-86cc-11e8-817f-f5517cf3607a.png)

It stucks here, and any of the debugging button work!

**Comment by rogalmic** [comment]
Can you try non-insider build for sanity check?

**Comment by antonio-petricca** [comment]
Sure! I have just tried with Code NON Insider, and it stucks in the same way.

**Comment by antonio-petricca** [comment]
Any other solution?!

**Comment by rogalmic** [comment]
2 ways to go from this point (assuming everything works correctly from commandline):
- you can try to narrow down the problem by commenting out parts of code and checking when it starts to work
- you can post the debug output here and/or provide the script if possible

**Comment by antonio-petricca** [comment]
Hi, I removed any content inside my script. 

I get this log:

> 7:39:02 AM, 7/16/2018
> From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code - Insiders","adapterID":"bashdb","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"})
> To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConditionalBreakpoints":false,"supportsConfigurationDoneRequest":false,"supportsEvaluateForHovers":true,"supportsStepBack":false,"supportsSetVariable":false}}
> From client: launch({"type":"bashdb","request":"launch","name":"Bash-Debug (hardcoded script name - Test)","cwd":"/home/antonio/projects/sisal/development/ci-template","program":"/home/antonio/projects/sisal/development/ci-template/test.sh","args":[],"showDebugOutput":true,"trace":true,"pathBash":"bash","pathBashdb":"bashdb","pathCat":"cat","pathMkfifo":"mkfifo","pathPkill":"pkill","__sessionId":"3a9abf17-0365-4413-abcc-3c9aa54333d0"})
> To client: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"(/home/antonio/projects/sisal/development/ci-template/test.sh:3):\n3:\techo Test!\n"}}
> (/home/antonio/projects/sisal/development/ci-template/test.sh:3):
> 3:	echo Test!
> To client: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"9997\n"}}
> 9997
> To client: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"############################################################\n"}}
> ############################################################
> To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
> To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"Sending InitializedEvent"}}
> To client: {"seq":0,"type":"event","event":"initialized"}
> From client: setBreakpoints({"source":{"name":"pipeline-configure","path":"/home/antonio/projects/sisal/development/ci-template/ci/scripts/pipeline-configure"},"lines":[254],"breakpoints":[{"line":254}],"sourceModified":false})
> To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"Sending StoppedEvent"}}
> To client: {"seq":0,"type":"event","event":"stopped","body":{"reason":"break","threadId":42}}
> To client: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"delete <>\n"}}
> delete <>
> To client: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"I don't understand \"load\".\n"}}
> I don't understand "load".
> To client: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"Please try again entering 'yes' or 'no'.\nI don't understand \"print\".\nPlease try again entering 'yes' or 'no'.\n"}}
> Please try again entering 'yes' or 'no'.
> I don't understand "print".
> Please try again entering 'yes' or 'no'.
> To client: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"I don't understand \"break\".\n"}}
> I don't understand "break".
> To client: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"Please try again entering 'yes' or 'no'.\n"}}
> Please try again entering 'yes' or 'no'.
> To client: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"I don't understand \"print\".\n"}}
> I don't understand "print".
> To client: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"Please try again entering 'yes' or 'no'.\n"}}
> Please try again entering 'yes' or 'no'.
> From client: threads(undefined)
> To client: {"seq":0,"type":"response","request_seq":4,"command":"threads","success":true,"body":{"threads":[{"id":42,"name":"Bash thread"}]}}
> From client: stackTrace({"threadId":42,"startFrame":0,"levels":20})
> From client: stackTrace({"threadId":42,"startFrame":0,"levels":20})
>

**Comment by rogalmic** [comment]
I am not sure why, but seems that bashdb does not support options 'load' or 'break' in the debugging console. You could try removing breakpoints/variables or installing newest bashdb.

I do not have access to pc, so cannot check this for some time...

**Comment by antonio-petricca** [comment]
As suggested by you, I have installed BASHDB from sources...

**Comment by rogalmic** [comment]
Please check if 'print' or 'break' options work from debugging console, when running bashdb directly...

**Comment by antonio-petricca** [comment]
```bash
$ bashdb pipeline-configure bash debugger, bashdb, release 4.4-0.94

Copyright 2002-2004, 2006-2012, 2014, 2016-2017 Rocky Bernstein
This is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.

(/home/antonio/pipeline-configure:5):
5:	if [ $# -lt 2 ]; then
bashdb<0> l
  1:    #!/bin/bash
  2:    
  3:    # Check parameter(s)
  4:    
  5: => if [ $# -lt 2 ]; then
  6:      SCRIPT_NAME=$(basename $0)
  7:      echo "${SCRIPT_NAME} [Root POM path (e.g. \"sw\")] [Jenkinsfile properties path (e.g. \"ci/settings\")]"
  8:      exit 1
  9:    fi
 10:    
bashdb<1> print $#
0
bashdb<2> break 6
Breakpoint 1 set in file /home/antonio/pipeline-configure, line 6.
bashdb<3>
```

**Comment by antonio-petricca** [comment]
I believe on this project, so I am going to take some time to debug your great extension on my development environment...

**Comment by wataash** [comment]
Hi @antonio-petricca,

You have to debugging by "Extension + Server":

![image](https://user-images.githubusercontent.com/4846670/42815494-7bd36200-8a02-11e8-81dd-ed3648543644.png)

and after another vscode launched, please set `"debugServer": 4711` in your `launch.json`, and run it.

Please see [official document](https://code.visualstudio.com/docs/extensions/example-debuggers#_development-setup-for-mock-debug) for details.

**Comment by antonio-petricca** [comment]
@wataash It works, now I can debug it!

**Comment by antonio-petricca** [comment]
I found the solution, [here is the pull request](https://github.com/rogalmic/vscode-bash-debug/pull/74).

Do you think to make it available as update early?

Thank you,
Antonio

**Comment by rogalmic** [comment]
Thanks! This needs to be fixed for newest bashdb version, so that is a very good finding.

I took some time and tested this on `bashdb, release 4.2-0.8`, it works there just giving a warning:
```
Removed 3 breakpoint(s).
** Undefined command "yes". Try "help".
```

I think it needs a bit more testing time with different bashdb versions, because I am a bit worried about breaking backwards compatibility. 

I think we can merge this, but lets wait with release for now.
@wataash : Do you agree?

**Comment by wataash** [comment]
agree :)

**Comment by antonio-petricca** [comment]
Hi, have you planned to release this fix?

**Comment by rogalmic** [comment]
Yes, I have not noticed any issues so far (though I did not spend much time testing), so we will release it. 

I will try to release that this week + I will update the dependencies and Readme (the default supported bashdb version will be 4.4).

**Comment by antonio-petricca** [comment]
Thank you!
