### ISSUE TITLE
Interactive scripting (prev. 'cannot spawn external terminal on Linux')

### ISSUE THREAD

**Issue by antonio-petricca** [rogalmic/vscode-bash-debug#75]
Hi, I have posted [a new issue](https://github.com/Microsoft/vscode/issues/54532) about spawing an external terminal on Linux...

**Comment by antonio-petricca** [comment]
VS Code team told me that this issue is caused by your plugin!!!!!!!

**Comment by antonio-petricca** [comment]
I have investigated, and I agree with VS Team: this extention does not support terminal.

Is there a workaround? In my scripts I have to check output or interact with user.

Thank you!
A.

**Comment by rogalmic** [comment]
Yes, this is current limitation, as stated in plugin description. 

There is a plan to add support for that, but this means probably a lot of work:
https://github.com/rogalmic/vscode-bash-debug/wiki/TODO-for-next-version

**Comment by rogalmic** [comment]
Test version pre-pre-alpha:
[bash-debug-0.2.4.vsix.zip](https://github.com/rogalmic/vscode-bash-debug/files/2366312/bash-debug-0.2.4.vsix.zip)

**Comment by rogalmic** [comment]
Done in master branch. Will be released after testing...

Package:
https://github.com/rogalmic/vscode-bash-debug/releases/tag/untagged-6e5b657f6c981df690c5
