### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by HexenZ** [rogalmic/vscode-bash-debug#76]
Hi, I'm having an issue with vscode-bash-debug, maybe it's just a matter of misconfiguration but I don't know were to go and I'll appreciate help. Having the following scripts:

```
#file1.sh
#!/bin/bash

echo 'hello'

. ./file2.sh
```
----------------------------
```
#file2.sh
#!/bin/bash

echo 'world'
```

The debugger isn't able to debug file2.sh. But changing '. ./file2.sh' to '/absolute/path/file2.sh' works fine.

launch.json:

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug (hardcoded script name)",
            "cwd": "${workspaceFolder}",
            "program": "${workspaceFolder}/file1.sh",
            "showDebugOutput": true,
            "trace": true,
            "args": []
        }
    ]
}

**Comment by HexenZ** [comment]
Any help please? Still looking for a solution

**Comment by rogalmic** [comment]
Sorry for late response:
1. why there is space between dots?
`. ./file2.sh`
2. try :
`source ./file2.sh` 
or 
`source ../file2.sh` 
depending the file location

**Comment by rogalmic** [comment]
You are correct, dot works as well...

Which version of bashdb/bash do you have? (I successfully tried on 4.4.0-94 and also build 91 + bash 4.4.19)

You could try installing newest bashdb:
https://github.com/rogalmic/vscode-bash-debug/issues/67

**Comment by HexenZ** [comment]
I'm using

bash: GNU bash, versión 4.4.19(1)-release (x86_64-pc-linux-gnu)
bashdb: bashdb, release 4.4-0.94

We're using the same or am I wrong?

**Comment by rogalmic** [comment]
Now this is interesting ...

Are you able to provide some snapshots + exact reproduction steps. Screen record would be ok as well. Can there be some issues with accessing the "sourced" file?

**Comment by HexenZ** [comment]
![shot1](https://user-images.githubusercontent.com/5945862/44401372-bd7e4000-a54e-11e8-8100-92563ba17f5f.png)
![shot2](https://user-images.githubusercontent.com/5945862/44401385-c40cb780-a54e-11e8-9348-a61bfec3e08d.png)
![shot3](https://user-images.githubusercontent.com/5945862/44401389-c7a03e80-a54e-11e8-9605-9bd4ed1ebee4.png)

The steps are:

1. Click 'Debug' -> 'Start Debuggin'
2. Press F5 (Continue)
3. The script finishes and the result is printed:

![shot4](https://user-images.githubusercontent.com/5945862/44401654-95dba780-a54f-11e8-8e06-8fcf69a2aaa6.png)

As I allready said it stops at the first breakpoint placed at a1.sh line 3 (echo hello) but it doesn't at the second a2.sh line 3 (echo world).

**Comment by rogalmic** [comment]
OK, so the reason is now obvious. When setting breakpoint source path when debugging, it does not accept paths with spaces nor slashes "-". 

I am talking "load" and "break" commands from http://bashdb.sourceforge.net/bashdb.html. 

Unfortunately wrapping path in " or ' or  ` does not seem to help when i change code of extension... Need to investigate more...

Please use path without "-" to verify this finding.

**Comment by rogalmic** [comment]
Issue reported:
https://sourceforge.net/p/bashdb/bugs/54/

**Comment by HexenZ** [comment]
I've changed the path name from "/home/adrian/test-shell" to "/home/adrian/testshell" and still having the same issue, it stops at the first break point but ignores the second.

There must be something else.

**Comment by rogalmic** [comment]
Please attach debug console output, when launch.json configuration has : 
"showDebugOutput": true,

**Comment by HexenZ** [comment]
This is the console output:

/home/adrian/testshell
 <$EUID> 
1000
 <$#> 
1
 <$0> 
/usr/bin/bashdb
 <$-> 
hBET
############################################################
continue
world
Debugged program terminated normally. Use q to quit or R to restart.
bash: línea 18: 21520 Terminado (killed)      "cat" "/tmp/vscode-bash-debug-fifo-11391" 1>&3  (dir ahora: ~)
bash: línea 18: 21521 Terminado (killed)      "cat"
     21522                       | "bashdb" --quiet --tty "/tmp/vscode-bash-debug-fifo-11391" -- "/home/adrian/testshell/a1.sh"

**Comment by rogalmic** [comment]
Hmm, this is weird. Bashdb actually stops, and "continue" is sent by debugger:
```
Breakpoint 3 hit (1 times).
(/home/adrian/testshell/a2.sh:3):
3: echo 'world'
############################################################
backtrace
->0 in file ./a2.sh' at line 3 ##1 source("./a2.sh") called from file/home/adrian/testshell/a1.sh' at line 5
##2 source("/home/adrian/testshell/a1.sh") called from file /usr/bin/bashdb' at line 99 ##3 main("--quiet", "--tty", "/tmp/vscode-bash-debug-fifo-11391", "--", "/home/adrian/testshell/a1.sh") called from file/usr/bin/bashdb' at line 0
############################################################
backtrace
->0 in file ./a2.sh' at line 3 ##1 source("./a2.sh") called from file/home/adrian/testshell/a1.sh' at line 5
##2 source("/home/adrian/testshell/a1.sh") called from file /usr/bin/bashdb' at line 99 ##3 main("--quiet", "--tty", "/tmp/vscode-bash-debug-fifo-11391", "--", "/home/adrian/testshell/a1.sh") called from file/usr/bin/bashdb' at line 0
############################################################
Program stopped.
It stopped at breakpoint 3.
```

Can you see callstack when debugger stops and console shows:

`->0 in file ./a2.sh' at line 3` ?

**Comment by HexenZ** [comment]
Yes, I've noticed that bashdb actually stops at the breakpoint and it seems that vs-code sends a "continue" instruction even if I'm running the option "Debug step by step".

Here's the callstack output:

->0 in file `./a2.sh' at line 3 (Unknown origin:3)
##1 source("./a2.sh") called from file `/home/adrian/testshell/a1.sh' at line 5 (/home/adrian/testshell/a1.sh:5)
##2 source("/home/adrian/testshell/a1.sh") called from file `/usr/bin/bashdb' at line 99 (/usr/bin/bashdb:99)
##3 main("--quiet", "--tty", "/tmp/vscode-bash-debug-fifo-13145", "--", "/home/adrian/testshell/a1.sh") called from file `/usr/bin/bashdb' at line 0 (/usr/bin/bashdb:0)

**Comment by rogalmic** [comment]
I am a bit confused, since continue can only be sent by vscode to extension, there is no other path for that.

So it seems that vscode calls the extension's callback containing "continue" by itself, without any user action?


Are you using mouse to click the debugger buttons or "F5"/"F10"/"F11" ?

**Comment by HexenZ** [comment]
I'm using F5 most of the time or the "play like" arrow:
![shot6](https://user-images.githubusercontent.com/5945862/44517643-8469db00-a6c8-11e8-945a-a97556efa690.png)
Anyway, every time I'm testing, I try every button or F* key.

**Comment by rogalmic** [comment]
What is the platform/system and VS code version?

I mean everything looks ok from debug session point of view, so we need to look for problem higher in stack...

**Comment by HexenZ** [comment]
SO: Ubuntu 18.04.1 LTS
VScode: 1.26.1

If you need any other info let me know :)

**Comment by rogalmic** [comment]
Some changes that might help:
[bash-debug-0.2.2.vsix.zip](https://github.com/rogalmic/vscode-bash-debug/files/2318263/bash-debug-0.2.2.vsix.zip)

**Comment by rogalmic** [comment]
Preparing for release, here is test version:
https://github.com/rogalmic/vscode-bash-debug/releases/download/untagged-eccd51e3096d87c7b498/bash-debug-0.2.2.vsix

**Comment by rogalmic** [comment]
I should thank you for patience :). Anyway, now the changes are released. 

For spaces to work in script path, bashdb upgrade will be needed, after it's next release (those scripts can also be updated manually with code fixes in /usr/share/bashdb/* ).
