### ISSUE TITLE
FAIL: test-bug-set-e

### ISSUE THREAD

**Issue by cooperfdiv** [rogalmic/vscode-bash-debug#78]
OS: Mac OS X 10.13.6
Bash version: GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
bashdb 4.4-0.94

FAIL: test-bug-set-e
bashdb: cannot read program to debug: /Users/dcooper/Downloads/bashdb-4.4-0.94/test/example/bug-set-e.sh.
--- /Users/dcooper/Downloads/bashdb-4.4-0.94/test/integration/bug-set-e.check 2018-08-10 10:40:36.000000000 -0500
+++ /Users/dcooper/Downloads/bashdb-4.4-0.94/test/data/bug-set-e.right 2017-07-31 23:43:16.000000000 -0500
@@ -1 +1,18 @@
-INVESTIGATE EXIT FAILURE: [1 => exit (1)]
+(bug-set-e.sh:2):
+2: x=1
++# Debugger test to see that set -e is respected and we can step through it
++step
+(bug-set-e.sh:4):
+4: set -e
++step
+(bug-set-e.sh:6):
+6: echo hi
++step
+hi
+(bug-set-e.sh:7):
+7: (( 1 / 0))
++step
+(bug-set-e.sh:1):
+1: #!/bin/bash
++quit
+bashdb: That's all, folks...
FAIL test-bug-set-e (exit status: 1)

**Comment by rogalmic** [comment]
Is this related to vscode extension, or just bashdb?
